export const INDEX = {
  PUBLIC: "",
  PROTECTED: "/app",
};

export const PARTIAL_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: (uid = ":uid", token = ":token") =>
    `/reset-password/${uid}/${token}`,


  FILES: "/files",
  ADD_FILE: "/add_file",
  BLOCKCHAIN: "/blockchain",
  VALIDATION: "/validation",
  DECRYPTION: "/decryption",
  API_KEYS: "/api_keys",
  BILLING: "/billing",
  ACCOUNT: "/account",
  FEEDBACK: "/feedback",
  NOT_FOUND: "*",
}

export const COMPLETE_PATHS = {
  LOGIN: `${INDEX.PUBLIC}${PARTIAL_PATHS.LOGIN}`,
  REGISTER: `${INDEX.PUBLIC}${PARTIAL_PATHS.REGISTER}`,
  FORGOT_PASSWORD: `${INDEX.PUBLIC}${PARTIAL_PATHS.FORGOT_PASSWORD}`,
  RESET_PASSWORD: (uid = ":uid", token = ":token") =>
    `${INDEX.PUBLIC}${PARTIAL_PATHS.RESET_PASSWORD(uid, token)}`,
  HOME: `${INDEX.PUBLIC}${PARTIAL_PATHS.HOME}`,
  FILES: `${INDEX.PROTECTED}${PARTIAL_PATHS.FILES}`,
  ADD_FILE: `${INDEX.PROTECTED}${PARTIAL_PATHS.ADD_FILE}`,
  BLOCKCHAIN: `${INDEX.PROTECTED}${PARTIAL_PATHS.BLOCKCHAIN}`,
  VALIDATION: `${INDEX.PROTECTED}${PARTIAL_PATHS.VALIDATION}`,
  DECRYPTION: `${INDEX.PROTECTED}${PARTIAL_PATHS.DECRYPTION}`,
  API_KEYS: `${INDEX.PROTECTED}${PARTIAL_PATHS.API_KEYS}`,
  BILLING: `${INDEX.PROTECTED}${PARTIAL_PATHS.BILLING}`,
  ACCOUNT: `${INDEX.PROTECTED}${PARTIAL_PATHS.ACCOUNT}`,
  FEEDBACK: `${INDEX.PROTECTED}${PARTIAL_PATHS.FEEDBACK}`,
  NOT_FOUND: PARTIAL_PATHS.NOT_FOUND,
};
